import { Injectable } from '@angular/core';
import { AsociacionService } from './asociacion.service';

@Injectable({
  providedIn: 'root'
})
export class ListsService {

  pais:any[]=[
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bosnia and Herzegovina",
    "Barbados",
    "Wallis and Futuna",
    "Saint Barthelemy",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "Bahrain",
    "Burundi",
    "Benin",
    "Bhutan",
    "Jamaica",
    "Bouvet Island",
    "Botswana",
    "Samoa",
    "Bonaire, Saint Eustatius and Saba ",
    "Brazil",
    "Bahamas",
    "Jersey",
    "Belarus",
    "Belize",
    "Russia",
    "Rwanda",
    "Serbia",
    "East Timor",
    "Reunion",
    "Turkmenistan",
    "Tajikistan",
    "Romania",
    "Tokelau",
    "Guinea-Bissau",
    "Guam",
    "Guatemala",
    "South Georgia and the South Sandwich Islands",
    "Greece",
    "Equatorial Guinea",
    "Guadeloupe",
    "Japan",
    "Guyana",
    "Guernsey",
    "French Guiana",
    "Georgia",
    "Grenada",
    "United Kingdom",
    "Gabon",
    "El Salvador",
    "Guinea",
    "Gambia",
    "Greenland",
    "Gibraltar",
    "Ghana",
    "Oman",
    "Tunisia",
    "Jordan",
    "Croatia",
    "Haiti",
    "Hungary",
    "Hong Kong",
    "Honduras",
    "Heard Island and McDonald Islands",
    "Venezuela",
    "Puerto Rico",
    "Palestinian Territory",
    "Palau",
    "Portugal",
    "Svalbard and Jan Mayen",
    "Paraguay",
    "Iraq",
    "Panama",
    "French Polynesia",
    "Papua New Guinea",
    "Peru",
    "Pakistan",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Saint Pierre and Miquelon",
    "Zambia",
    "Western Sahara",
    "Estonia",
    "Egypt",
    "South Africa",
    "Ecuador",
    "Italy",
    "Vietnam",
    "Solomon Islands",
    "Ethiopia",
    "Somalia",
    "Zimbabwe",
    "Saudi Arabia",
    "Spain",
    "Eritrea",
    "Montenegro",
    "Moldova",
    "Madagascar",
    "Saint Martin",
    "Morocco",
    "Monaco",
    "Uzbekistan",
    "Myanmar",
    "Mali",
    "Macao",
    "Mongolia",
    "Marshall Islands",
    "Macedonia",
    "Mauritius",
    "Malta",
    "Malawi",
    "Maldives",
    "Martinique",
    "Northern Mariana Islands",
    "Montserrat",
    "Mauritania",
    "Isle of Man",
    "Uganda",
    "Tanzania",
    "Malaysia",
    "Mexico",
    "Israel",
    "France",
    "British Indian Ocean Territory",
    "Saint Helena",
    "Finland",
    "Fiji",
    "Falkland Islands",
    "Micronesia",
    "Faroe Islands",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Namibia",
    "Vanuatu",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "New Zealand",
    "Nepal",
    "Nauru",
    "Niue",
    "Cook Islands",
    "Kosovo",
    "Ivory Coast",
    "Switzerland",
    "Colombia",
    "China",
    "Cameroon",
    "Chile",
    "Cocos Islands",
    "Canada",
    "Republic of the Congo",
    "Central African Republic",
    "Democratic Republic of the Congo",
    "Czech Republic",
    "Cyprus",
    "Christmas Island",
    "Costa Rica",
    "Curacao",
    "Cape Verde",
    "Cuba",
    "Swaziland",
    "Syria",
    "Sint Maarten",
    "Kyrgyzstan",
    "Kenya",
    "South Sudan",
    "Suriname",
    "Kiribati",
    "Cambodia",
    "Saint Kitts and Nevis",
    "Comoros",
    "Sao Tome and Principe",
    "Slovakia",
    "South Korea",
    "Slovenia",
    "North Korea",
    "Kuwait",
    "Senegal",
    "San Marino",
    "Sierra Leone",
    "Seychelles",
    "Kazakhstan",
    "Cayman Islands",
    "Singapore",
    "Sweden",
    "Sudan",
    "Dominican Republic",
    "Dominica",
    "Djibouti",
    "Denmark",
    "British Virgin Islands",
    "Germany",
    "Yemen",
    "Algeria",
    "United States",
    "Uruguay",
    "Mayotte",
    "United States Minor Outlying Islands",
    "Lebanon",
    "Saint Lucia",
    "Laos",
    "Tuvalu",
    "Taiwan",
    "Trinidad and Tobago",
    "Turkey",
    "Sri Lanka",
    "Liechtenstein",
    "Latvia",
    "Tonga",
    "Lithuania",
    "Luxembourg",
    "Liberia",
    "Lesotho",
    "Thailand",
    "French Southern Territories",
    "Togo",
    "Chad",
    "Turks and Caicos Islands",
    "Libya",
    "Vatican",
    "Saint Vincent and the Grenadines",
    "United Arab Emirates",
    "Andorra",
    "Antigua and Barbuda",
    "Afghanistan",
    "Anguilla",
    "U.S. Virgin Islands",
    "Iceland",
    "Iran",
    "Armenia",
    "Albania",
    "Angola",
    "Antarctica",
    "American Samoa",
    "Argentina",
    "Australia",
    "Austria",
    "Aruba",
    "India",
    "Aland Islands",
    "Azerbaijan",
    "Ireland",
    "Indonesia",
    "Ukraine",
    "Qatar",
    "Mozambique"
];


  expediciones:any = [
    { valor:'LP' },
    { valor:'CB' },
    { valor:'SC' },
    { valor:'OR' },
    { valor:'PT' },
    { valor:'PD' },
    { valor:'BN' },
    { valor:'TJ' }
  ];

  // ueducativas:any[] = [
  //   {value:1, name:'German Busch'},
  //   {value:2, name:'Gabriel Rene Moreno'},
  //   {value:3, name:'Juana Azurduy de Padilla'},
  //   {value:4, name:'Mariscal Santa Cruz'}
  // ];
  //ueducativas:any;

  // sindicatos:any[]=[
  //   {value:1, name:'Taxis Montero'},
  //   {value:2, name:'24 de Septiembre'},
  //   {value:3, name:'Estrella del norte'},
  //   {value:4, name:'Radiotaxis Cruz del Sur'}
  // ];

  tservicios: any[] = [
   'Mototaxi',
   'Torito'
  ];
  
  tsangre:any[] = [
    {value:'A+', name:'A+'},
    {value:'O+', name:'O+'},
    {value:'B+', name:'B+'},
    {value:'AB+', name:'AB+'},
    {value:'A-', name:'A-'},
    {value:'O-', name:'O-'},
    {value:'B-', name:'B-'},
    {value:'AB-', name:'AB-'},
  ];

  categorias:string[] = [
    'A',
    'B',
    'C',
    'M',
    'P',
    'T'
  ]

  ciudades:string[]=[
    'Montero',
    'Warnes',
    'Santa Cruz de la Sierra',
    'Urubo',
    'Cotoca',
    'San Ignacio',
    'La Guardia',
    'Roboré',
    'Camiri',
    'Concepcion',
    'Puerto Quijarro',
    'Yapacani',
    'Puerto Suarez'
  ]

  colores:string[]=[
    'Azul',
    'Amarillo',
    'Blanco',
    'Cafe',
    'Negro',
    'Rojo',
    'Gris','Plata', 'Dorado', 'Beige', 'Cafe', 'Verde',
    'Otro'
  ]

  generos:any[]=['MASCULINO', 'FEMENINO'];

  grados:any[]=[
    {value:'administrador', label:'Administrador'},
    {value:'sarg_primero', label:'Sargento Primero'},
    {value:'sarg_segundo', label:'Sargento Segundo'},
    {value:'cabo', label:'Cabo'},
    {value:'sof_primero', label:'Suboficial Primero'},
  ]

  states_user = [
    {value:true, label:'Habilitado'},
    {value:false, label:'Deshabilitado'}
  ]

  roles_user = [
    {value:'administrador', label:'Administrador'},
    {value:'usuario', label:'Usuario'}
  ]

  departamentos = [
    {value:'LP', label:'LA PAZ'},
    {value:'OR', label:'ORURO'},
    {value:'PT', label:'POTOSÍ'},
    {value:'CB', label:'COCHABAMBA'},
    {value:'CH', label:'CHUQUISACA'},
    {value:'TJ', label:'TARIJA'},
    {value:'PD', label:'PANDO'},
    {value:'BN', label:'BENI'},
    {value:'SC', label:'SANTA CRUZ'},
  ]
}
