insert into conductor (ci, expedicion, nombres, apellidos, genero, id_asociacion, id_ueducativa) 
values (286421, 'SC', 'Antonio', 'Bejarano Contreras', 1, 4, 2),
(286422, 'SC', 'Brenda Cecilia', 'Duarte Espejo', 0, 4, 3),
(286423, 'SC', 'Carlos Delfin', 'Fernandez Gandia', 1, 5, 4),
(286424, 'SC', 'Hilda', 'Jimenez Lima', 0, 7, 8),
(286425, 'SC', 'Mario Nelio', 'Ordoñez Perez', 1, 14, 10),
(286426, 'SC', 'Ruben Silverio', 'Tapia Humerez', 1, 22, 2),
(286427, 'SC', 'Valentina Wendy', 'Yañez Zurita', 0, 23, 3),
(286428, 'SC', 'Alberto Brandon', 'Casas Diaz', 1, 24, 4),
(286429, 'SC', 'Ernesto', 'Felipez Guachalla', 1, 25, 8),
(286410, 'SC', 'Olga', 'Illimani Juarez', 0, 26, 10)

conductores del 48 al 57

insert into vehiculo (placa, tipo, id_conductor) 
values ('4523HJG','Bus Escolar', 48),
('1225ARO','Bus Universitario', 49),
('5622RTG','Gondola', 50),
('342FAS','Taxi Escolar', 51),
('4244BGB','Taxi Libre', 52),
('2343FTT','Trufi', 53),6
('4422TYU','Otro', 54),
('1233TRG','Bus Escolar', 55),
('3433UIL','Bus Universitario', 56),
('3255BNH','Gondola', 57)

insert into unidad_educativa (nombre) values ('Jose Maria Achá'),
('Colegio San Agustin'),
('Colegio Mayor San Lorenzo'),
('Colegio Saint Jorge'),
('Colegio Parroquial La Santa Cruz'),
('Colegio Británico Santa Cruz'),
('Colegio Santo Tomas de Aquino SCZ'),
('Colegio Aleman'),
('Colegio Catolico SCZ'),
('Alexander Von Humboldt Santa Cruz'),
('Colegio Saint Patrick'),
('Colegio Maria Goretti'),
('Las Palmas School'),
('Modulo Educativo Marcelo Quiroga Santa Cruz'),
('Colegio Cema CIFA'),
('Colegio El Fuerte'),
('Unidad Educativa Luz del Mundo'),
('Colegio Emanuel'),
('Colegio Hernan Gmeiner'),
('Colegio Iberoamericano')

insert into asociacion (nombre) values ('Sindicato de Transporte Mixto El Soyero Santa Cruz - Paylon'),
('Sindicato de Tranportistas Santa Cruz'),
('Radiotaxis Milenium'),
('Radiotaxis SAO'),
('Trufi Cabeza'),
('Trufi Montero'),
('Expreso Samaipata'),
('Cooperativa de Micros 24 de Septiembre'),
('FRANECAR'),
('Radiomovil Viru Viru'),
('Radiomovil La Cuba'),
('Radiomovil Servicruz SRL'),
('Radiomovil PARMA'),
('Radiomovil Clasico'),
('Las Palmas Radiomovil'),
('Radiomovil Seguro'),
('Radiomovil La Diligencia'),
('Radiomovil Motacu'),
('Radiomovil Rio Verde'),
('Radiomovil Pahuichi'),
('Radiotaxi el nuevo Urubo'),
('Trans Minibus Gutierrez'),
('CONSUTRANS'),
('Radiomovil Valencia')8